### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by tcervo** [petewarden/iPhoneTracker#14]
Sorry for the silly question, but...I saw the closed issue where someone was just opening the index.html file, and was told to "run the app". I don't see an app anywhere, though. All I've got are a bunch of .m., .h, .xcodeproj, etc. files. Where's the binary? What am I missing?

**Comment by parkr** [comment]
This is the source file directory. Do you have Xcode? If so, open up the .xcodeproj and click "Build and Run". If not, go to the [pages](http://petewarden.github.com/iPhoneTracker/) and [download the binary](http://static.openheatmap.com.s3.amazonaws.com/iPhoneTracker.app.zip) that has already been compiled.

**Comment by NikolasE** [comment]
Could you also provide binaries for the older Mac Os Versions? I'm running an intel-based 10.5.8 MacBook which is not supported by the given binary.

**Comment by tcervo** [comment]
Ah, ok...totally missed the link to the app. All I saw (at first) were the two giant download icons at the top...which download the source code only.

**Comment by petewarden** [comment]
Sorry about that. For a while we had links to the source code as a zip file
at the top of the page (the default github setup) but those were confusingly
unlabeled. The actual app is at the  Download the Application link -
http://static.openheatmap.com.s3.amazonaws.com/iPhoneTracker.app.zip

Hope that helps,
                        Pete
