### ISSUE TITLE
Not loading with Chrome on 10.6.7

### ISSUE THREAD

**Issue by julesmoretti** [petewarden/iPhoneTracker#18]
Hi Pete:

I heard about this at work which fascinates me of course. Unfortunately I cant seem to make it work. Here is what I did so far, perhaps you can let me know if I am missing something, thank you.

• I have my iphone 4 (Verizon) backed up on my macbook pro itunes.
• Downloaded your package
• Ran the index.html opening with google chrome
• See a map with a spinning loading wheel but at that point nothing happens, it just keep spinning.

So is there something that I am suppose to be doing that I have not understood?

Thank you for your suggestions.

Appreciated.

Jules

**Comment by awkale** [comment]
you downloaded the source code. just download the application and launch it.
http://static.openheatmap.com.s3.amazonaws.com/iPhoneTracker.app.zip

**Comment by julesmoretti** [comment]
Thank you very much for pointing that out.

**Comment by petewarden** [comment]
Unfortunately it looks like the Verizon iPhones store their data in a
slightly different format. We have a fix in the pipeline, but don't have an
ETA on that yet, sorry.

cheers,
           Pete
