### ISSUE TITLE
No tracking outside US?

### ISSUE THREAD

**Issue by ld26464** [petewarden/iPhoneTracker#30]
I don't believe this is pulling down info while I am outside the US. I've used the phone in both Europe and Asia during the reporting period. Though the trips might be falling into some of the time gaps noted. Another possibility is that the overseas cell systems do not track the same way. Is there any info as to whether this works the same on Verizon and ATT as they are different systems. 

Probably good idea for legal reasons, but it implies that this is may be being done with approval from the Apple Legal department.

**Comment by petewarden** [comment]
We do know from both Alasdair and my data that it's tracking some points
from the UK at least, and we've had reports from other countries too. It
sounds like it's not doing that for you though?

**Comment by justy** [comment]
I live in Australia and it works as advertised.

**Comment by marookkenja** [comment]
It works fine for every one here in DK as well, so it must be a local issue on the phone, like disabled roaming or the likes...

**Comment by ld26464** [comment]
That's probably it. I usually disable everything but cell roaming.
