### ISSUE TITLE
Stuck on "Loading"

### ISSUE THREAD

**Issue by jcastanza** [petewarden/iPhoneTracker#9]
I've tried opening index.html in Firefox and Safari, and it just shows the map with nothing on it, and the spinning progress indicator which is labeled "Loading".  I've waited as long as 10 minutes and nothing happens?

**Comment by parkr** [comment]
From what I understand, you have to launch the app to be able to read the date. `index.html` is merely a template which is loaded by the app.

**Comment by jcastanza** [comment]
Doh.  Thank you.

**Comment by petewarden** [comment]
Sorry about that. It sounds like you might have downloaded the source code
bundle, which we had confusing links to near the title. The right link is
http://static.openheatmap.com.s3.amazonaws.com/iPhoneTracker.app.zip

Hope that helps,

Pete
